version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://<YOUR_DB_HOST>:3306/goodjob
      - SPRING_DATASOURCE_USERNAME=<YOUR_DB_USER>
      - SPRING_DATASOURCE_PASSWORD=<YOUR_DB_PASSWORD>
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    networks:
      - goodjob-net

networks:
  goodjob-net:
    driver: bridge